### ISSUE TITLE
Square Minimap Buttons grabbing non-buttons

### ISSUE THREAD

**Issue by SerendipityJones** [Azilroka/ProjectAzilroka#44]
1) In version 1.86, there is a blank button which I suspect may be the mail icon returning to the bar (except not showing up when there's no mail). See image below.

2) However, it's also grabbing map icons such as arrows and dots, so I can't tell where I am on the minimap or where the thing I'm trying to go to is. 

![image](https://user-images.githubusercontent.com/59793669/215307822-d603fbf8-4762-41ae-b091-dea0d49df320.png)

Note the third and last icons in the column -- they should be staying on the minimap, as indeed they always used to!

3) Also, the Dragon Isles Summary/Garrison/Etc button usually sits itself in the corner of the map until and unless I reload the UI, and then it jumps into proper place in the bar. That's been going on at least since Dragonflight started -- it happened once in a while before, but since then it's every or virtually every time.

![image](https://user-images.githubusercontent.com/59793669/215327452-4788a943-8ff4-4633-a9bc-9d600e896327.png)

Here are my settings:
![image](https://user-images.githubusercontent.com/59793669/215307930-43d7cd8f-e49e-4459-9342-f34f883e20a6.png)

I wasn't sure if these should be separate bug reports but since they're all regarding the minimap bar and I think #2 may have arrived in the process of #1 being partially fixed, I decided to put them together. I hope that's okay.

Thank you!

**Comment by AnbuFozzy** [comment]
![squaresetting](https://user-images.githubusercontent.com/112737898/215349646-644ffedd-436b-4026-b22d-e48e964be325.JPG)
![squarebug](https://user-images.githubusercontent.com/112737898/215349648-6dad6a04-8a10-4871-a60f-4812eb380ebd.JPG)

Same issue here. All of my mining nodes, treasure chests and even Tomtom's waypoint are being grabbed.
Version 1.86-19

**Comment by Taizunz** [comment]
For anyone on the alpha branch who is affected by this, it seems like this issue cropped up in 1.86-13
You can revert to 1.86-12 to "fix it".
How to in Curseforge:
https://user-images.githubusercontent.com/15648000/215351280-337a3936-6044-4bcd-bce9-a180b5ad401f.mp4

**Comment by Azilroka** [comment]
I fixed TomTom.. Let me know what other addon is broken. I'm trying to fix the botched detection of some minimap icons that hit my partial list

**Comment by Taizunz** [comment]
Zygor , HandyNotes and TomTom icons were the main ones that I had issues with.
Looking at f6b79720dd7c4140ea1cb2810b526b443985ecef I'll probably have to test GatherMate2 as well.

**Comment by SerendipityJones** [comment]
My other broken one there -- the higher arrow -- is Handy Minimap Arrow (https://www.curseforge.com/wow/addons/handy-minimap-arrow).

This new version does fix the TomTom stuff!  My mail icon still seems to not be going in place, though that is sort of the opposite issue:
![image](https://user-images.githubusercontent.com/59793669/215382767-888dc6e5-7857-478a-9b3e-ca9aabd73b11.png)
![image](https://user-images.githubusercontent.com/59793669/215382795-18bfda9f-3ea0-481d-aabd-4aaad38cefd1.png)

**Comment by Taizunz** [comment]
I'm on 1.86-22 and it still appears to be grabbing TomTom pins.
![image](https://user-images.githubusercontent.com/15648000/215460375-f3a23941-c9ee-4a60-aea3-e4b4c1665a3a.png)

**Comment by Azilroka** [comment]
What version of TomTom?

**Comment by Taizunz** [comment]
3.3.5

**Comment by Taizunz** [comment]
And HandyNotes is also being grabbed on 1.86-22. It was specifically a rare pin from this HandyNotes plugin: https://github.com/zarillion/handynotes-plugins/tree/master/plugins/10_Dragonflight

**Comment by Azilroka** [comment]
I'd probably have to get the data from you or get there on my rogue which I'm trying to progress through now.

I'd have to give you the code when I get home to get to it.

**Comment by Taizunz** [comment]
I'd be happy to help troubleshoot further.
Feel free to DM me on Discord (Taizun#0001) if that's easier for you. I'm on the Tukui Discord as well, so you should be able to.

**Comment by SerendipityJones** [comment]
My TomTom pins seem to be in there again too today... I'm on 1.86-23-g4f5317b and TomTom 3.3.5 (1/27 release) right now. Let me know if there are any other specific things it would help to know!

**Comment by Azilroka** [comment]
Hopefully that one fixes it.. I logged into Wrath this time and mine was fine.

**Comment by SerendipityJones** [comment]
The TomTom pins and arrows do indeed seem to be fixed, thank you!

Unfortunately, the Handy Minimap Arrow is still ending up in the minimap bar, which makes it very hard to navigate. I'd rather not get rid of it, because it moves the arrow to a layer above all the little icons on the map instead of under them and that really helps me.

The Dragon Isles Summary is still sitting in the map instead of the bar until and unless I do a /reload, and the mail icon has not returned to the minimap bar. Should I make separate issues for those?

**Comment by Taizunz** [comment]
Hovering over HandyNotes icons to display more detailed map graphics makes it behave weirdly since these SMB changes were introduced.

![Discord_2022-10-05_16-38-05-output](https://user-images.githubusercontent.com/15648000/216886149-0cf29806-70a6-4a2e-9536-005455006031.gif)

**Comment by Taizunz** [comment]
And when I have clicked a HandyNotes icon that has more detailed graphics to make it stick, SMB also grabs it as buttons.
![image](https://user-images.githubusercontent.com/15648000/216897208-b8a99599-ab57-4ee9-9de3-20ebb3aff630.png)

**Comment by Azilroka** [comment]
The only way it would affect that map is if it isn't reparented to that map.. which I doubt is the case.

Now I believe the other part grabbing those.

**Comment by Taizunz** [comment]
I have no clue what that means. I'm not a developer/programmer.

All I know is that these issues cropped up after f6b79720dd7c4140ea1cb2810b526b443985ecef

**Comment by Azilroka** [comment]
Because I took out the partial name matching which stop some minimap icons from being moved into the bar.

**Comment by Translitdk** [comment]
Having [similar](https://i.imgur.com/IMA9jzR.gif) issue with https://www.curseforge.com/wow/addons/gatherlite

**Comment by Pootch** [comment]
I  have the same problem as @Translitdk with gatherlite oder gathermate2.
The square Minimap buttons disable the nodes visiblity on the minimap and also shows them as buttons for each node.
Disabling the square minimap buttons, solves the problem.

**Comment by Azilroka** [comment]
I haven't checked Gatherlite but will do it this weekend.

**Comment by Pootch** [comment]
> I haven't checked Gatherlite but will do it this weekend.

This wasn't fixed in the latest version 1.87.2, right? Still having this issue.
I had no issue with this in wow patch 3.4.0 and probably 1.86.xx (ProjectAzilroka)
